apiVersion: apps/v1
kind: Deployment
metadata:
  name: joomla-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: joomla
  template:
    metadata:
      labels:
        app: joomla
    spec:
      containers:
      - name: joomla
        image: joomla
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: joomla-service
spec:
  selector:
    app: joomla
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80


